groups:
  - name: solana-alerts
    rules:
      - alert: SolanaBalanceThreasholdCatchAll
        expr: solana_account_balance{type="sol",account="web-prod",is_maker="false"} < 1
        labels:
          severity: critical
        annotations:
          title: 'SOL Balance Low!'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          address: '{{ $labels.address }}'
          description: 'SOL Balance has reached critical threshold of 1. Currently - ({{ $value }}) SOL'

      - alert: LazySignerSolanaBalanceThreashold
        expr: solana_account_balance{type="sol",name="lazy_signer",account="web-prod"} < 250
        labels:
          severity: warning
        annotations:
          title: 'Lazy Signer SOL Balance'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          address: '{{ $labels.address }}'
          description: 'SOL balance has reached warning threshold of 500. Currently - ({{ $value }}) Sol'

      - alert: OracleSolanaBalanceThreashold
        expr: solana_account_balance{type="sol",name="oracle",account="web-prod"} < 20
        labels:
          severity: warning
        annotations:
          title: 'Oracle SOL Balance'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          address: '{{ $labels.address }}'
          description: 'SOL Balance has reached warning threshold of 20. Currently - ({{ $value }}) SOL'

      - alert: CircuteBreakerCatchAllGreaterThan50
        expr: solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 > 50 and solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 < 75
        labels:
          severity: warning
        annotations:
          title: 'Circuit Breaker Greater Than 50%'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Circuit Breaker has reached warning threshold of > 50%! Currently - ({{ $value }})%'

      - alert: CircuteBreakerCatchAllGreaterThan75
        expr: solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 > 75 and solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 < 100
        labels:
          severity: warning
        annotations:
          title: 'Circuit Breaker Greater Than 75%'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Circuit Breaker has reached warning threshold of > 75%! Currently - ({{ $value }})%'

      - alert: CircuteBreakerCatchAllGreaterThan100
        expr: solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 > 100
        labels:
          severity: critical
        annotations:
          title: 'Circuit Breaker Greater Than 100%'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Circuit Breaker has reached critical threshold of > 100%! Currently - ({{ $value }})%'
