groups:
  - name: solana-alerts
    rules:
      - alert: IntegrityCheckCorrectedRecords
        expr: round(increase(integrity_check{account="oracle-prod"}[5m])) > 0
        labels:
          severity: warning
        annotations:
          title: 'Integrity Check Corrected Records!'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Integrity Check Corrected {{ $value }} Records'

      - alert: SolanaBalanceThreasholdCatchAll
        expr: solana_account_balance{type="sol",account="web-prod",is_maker="false"} < 1
        labels:
          severity: critical
        annotations:
          title: 'SOL Balance Low!'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          address: '{{ $labels.address }}'
          description: 'SOL Balance has reached critical threshold of 1. Currently - ({{ $value }}) SOL'

      - alert: SolanaBalanceThreasholdLazySigner
        expr: solana_account_balance{type="sol",name="lazy_signer",account="web-prod"} < 50
        labels:
          severity: warning
        annotations:
          title: 'Lazy Signer SOL Balance'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          address: '{{ $labels.address }}'
          description: 'SOL balance has reached warning threshold of 50. Currently - ({{ $value }}) Sol'

      - alert: SolanaBalanceThreasholdOracle
        expr: solana_account_balance{type="sol",name="oracle",account="web-prod"} < 20
        labels:
          severity: warning
        annotations:
          title: 'Oracle SOL Balance'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          address: '{{ $labels.address }}'
          description: 'SOL Balance has reached warning threshold of 20. Currently - ({{ $value }}) SOL'

      - alert: CircuitBreakerEnsureEndEpoch
        expr: (solana_circuit_breaker_level{account="web-prod", name=~"iot_mint|mobile_mint"} / solana_circuit_breaker_limit{account="web-prod", name=~"iot_mint|mobile_mint"} < 0.08) and ON() hour() == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          title: 'End Epoch Never Moved Circuit Breaker'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Circuit Breaker has not increased. Ensure End Epoch was successful'

      - alert: CircuitBreakerCatchAllGreaterThan50
        expr: solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 > 50 and solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 < 75
        labels:
          severity: warning
        annotations:
          title: 'Circuit Breaker Greater Than 50%'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Circuit Breaker has reached warning threshold of > 50%! Currently - ({{ $value }})%'

      - alert: CircuitBreakerCatchAllGreaterThan75
        expr: solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 > 75 and solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 < 100
        labels:
          severity: warning
        annotations:
          title: 'Circuit Breaker Greater Than 75%'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Circuit Breaker has reached warning threshold of > 75%! Currently - ({{ $value }})%'

      - alert: CircuitBreakerCatchAllGreaterThan100
        expr: solana_circuit_breaker_level{account="web-prod"} / solana_circuit_breaker_limit{account="web-prod"} * 100 > 100
        labels:
          severity: critical
        annotations:
          title: 'Circuit Breaker Greater Than 100%'
          account: '{{ $labels.account }}'
          name: '{{ $labels.name }}'
          description: 'Circuit Breaker has reached critical threshold of > 100%! Currently - ({{ $value }})%'
