apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/helium/helium-foundation-k8s
    targetRevision: HEAD
    path: ${path}
    directory:
      recurse: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://${argo_url}
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: ${google_client_id}
        clientSecret: ${google_client_secret}
      type: oidc
      id: google
      name: Google
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    ${argo_admins}
  scopes: "[email, group]"
